version: '3'

services:
  server:
    image: node:10.10.0
    command: ["npm", "start"]
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=50051
    working_dir: /app
    volumes:
      - .:/app
  nodejs:
    image: node:10.10.0
    command: ["node", "clients/nodejs/client.js"]
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    working_dir: /app
    volumes:
      - .:/app
  python:
    image: python:3.7.0
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    working_dir: /app
    volumes:
      - .:/app
