version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    command: ["npm", "start"]
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=50051
    volumes:
      - .:/app
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    command: ["node", "clients/nodejs/client.js"]
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    volumes:
      - .:/app
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    command: ["python", "clients/python/client.py"]
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    volumes:
      - .:/app
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    command: ["ruby", "clients/ruby/client.rb"]
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051
    volumes:
      - .:/app
