# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greeter.proto',
  package='greeter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgreeter.proto\x12\x07greeter\"\x15\n\x05Human\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Greeting\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x0eGreeterService\x12*\n\x05Hello\x12\x0e.greeter.Human\x1a\x11.greeter.Greetingb\x06proto3')
)




_HUMAN = _descriptor.Descriptor(
  name='Human',
  full_name='greeter.Human',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='greeter.Human.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=47,
)


_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='greeter.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greeter.Greeting.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['Human'] = _HUMAN
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Human = _reflection.GeneratedProtocolMessageType('Human', (_message.Message,), dict(
  DESCRIPTOR = _HUMAN,
  __module__ = 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.Human)
  ))
_sym_db.RegisterMessage(Human)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), dict(
  DESCRIPTOR = _GREETING,
  __module__ = 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.Greeting)
  ))
_sym_db.RegisterMessage(Greeting)



_GREETERSERVICE = _descriptor.ServiceDescriptor(
  name='GreeterService',
  full_name='greeter.GreeterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=78,
  serialized_end=138,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='greeter.GreeterService.Hello',
    index=0,
    containing_service=None,
    input_type=_HUMAN,
    output_type=_GREETING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETERSERVICE)

DESCRIPTOR.services_by_name['GreeterService'] = _GREETERSERVICE

# @@protoc_insertion_point(module_scope)
